### ISSUE TITLE
OGD Lizenzcodes for Datasetmetada

### ISSUE THREAD

**Issue by Andreasr28** [GDI-HE/Mapbender2.8#10]
Dataset metadata records generated from the geoportal must, in addition to the harvest to GDI-DE and INSPIRE, also be available for GovData (OpenData). Here it seems that an older licence code is still used in the corresponding module.

This is shown by the fact that the metadata in the GovData portal is not displayed as free as expected.

Peter Kochmann from GDI-DE NRW wrote, referring to the example from GovData-Portal: INSPIRE HE Verkehrsnetze ALKIS  
The current JSOn entry contains: dl-de-zero-2.0 but expectedt is: dl-zero-de/2.0 
https://wiki.gdi-de.org/display/gdk/Anbindung+der+GDI-DE+an+GovData

Example datasetmetadata Geoportal Hessen 
https://www.geoportal.hessen.de/mapbender/php/mod_exportIso19139.php?url=https%3A%2F%2Fwww.geoportal.hessen.de%2Fmapbender%2Fphp%2Fmod_dataISOMetadata.php%3FoutputFormat%3Diso19139%26id%3Dbc203846-ee8f-407e-b693-da567c200720&outputFormat=iso19139

```
<gmd:resourceConstraints>
<gmd:MD_LegalConstraints>
<gmd:useConstraints>
<gmd:MD_RestrictionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions"/>
</gmd:useConstraints>
<gmd:otherConstraints>
<gco:CharacterString>
Der automatisierte Abruf und die Nutzung der Geobasisdaten und der zugehörigen Metadaten sind kostenfrei. (§ 24 Hessisches Vermessungs- und Geoinformationsgesetz - HVGG) - Lizenz: dl-de-zero-2.0 - Datenlizenz Deutschland - Zero - Version 2.0 - https://www.govdata.de/dl-de/zero-2-0
</gco:CharacterString>
</gmd:otherConstraints>
<gmd:otherConstraints>
<gco:CharacterString>
{"id":"dl-de-zero-2.0","name":"Datenlizenz Deutschland - Zero - Version 2.0","url":"https:\/\/www.govdata.de\/dl-de\/zero-2-0"}
</gco:CharacterString>
</gmd:otherConstraints>
</gmd:MD_LegalConstraints>
```

Probably affected module: mod_exportIso19139.php

**Comment by karlbrink** [comment]
i have fixed the termsofuse entries in our Metadata-Editors.
