### ISSUE TITLE
Metadata kontakt_geoportal_rlp_de

### ISSUE THREAD

**Issue by karlbrink** [GDI-HE/Mapbender2.8#17]
fix wrong email address in some metadata generator scripts and mobilemap:

- /http/extensions/mobilemap/help/help_en.html
- /http/extensions/mobilemap/help/help_de.html
- /http/extensions/mobilemap/query/mapserver/wms_dhm_template.map
- **/http/php/mod_dataISOMetadata.php**
- **/http/php/mod_layerISOMetadata.php**
- /http/php/mod_syncCkan_server.php
- **/http/php/mod_featuretypeISOMetadata.php**
- **/http/php/mod_inspireDownloadFeed.php**
- **/http/php/mod_inspireAtomFeedISOMetadata.php**
- /http/geoportal/metadata_templates/mb_group_contact.xml

**Comment by Andreasr28** [comment]
Fix into -- gdi-hessen@hvbg.hessen.de ?

**Comment by karlbrink** [comment]
yes, this would be nice.

**Comment by Andreasr28** [comment]
TEstsystem

[kontakt@geoportal.rlp.de](mailto:kontakt@geoportal.rlp.de) was replaced "hardcoded" with [gdi-hessen@hvbg.hessen.de](mailto:gdi-hessen@hvbg.hessen.de)

/http/extensions/mobilemap/help/help_en.html line 68 also addres changed
/http/extensions/mobilemap/help/help_de.html line 68 also addres changed
/http/extensions/mobilemap/query/mapserver/wms_dhm_template.map ! we are not running and not owning this service, so in my opinion the metadata had to be rlp
/http/php/mod_dataISOMetadata.php line 558
/http/php/mod_layerISOMetadata.php line 446
/http/php/mod_syncCkan_server.php line 446
/http/php/mod_featuretypeISOMetadata.php line 324
/http/php/mod_inspireDownloadFeed.php line 534
/http/php/mod_inspireAtomFeedISOMetadata.php line 283
/http/geoportal/metadata_templates/mb_group_contact.xml line 35

**Comment by muqit-zoarder** [comment]
@Andreasr28 
As you changed the email in required places already , so should I push these changes in [17_Metadata_kontakt_geoportal_rlp_de] branch or it is not needed?
