### ISSUE TITLE
Login no longer works after application update

### ISSUE THREAD

**Issue by Andreasr28** [GDI-HE/Mapbender2.8#20]
Login no longer works after application update. This is tested for: 
https://www.geoportal.hessen.de/
and
https://test.geoportal.hessen.de/

**Comment by Andreasr28** [comment]
Web developer cosnsole shows no errors .. but the presentation in the application suggests a successful login,
by displaying the registration successful banner.

In fact, no function is available for registered users.
- no Profil - no Admingui ect.

**Comment by Andreasr28** [comment]
May be some changes in  .. /mapbender/geoportal/authentication.php

**Comment by karlbrink** [comment]
- [ ] fix it in production and test
- [ ] doublecheck the corresponding commit

i fixed it now by rewinding one commit https://github.com/GDI-HE/GeoPortal.rlp/commit/55c9b65e9e232f77e095b0b14c91359cec71691f from the community edition in our system....
i will doublecheck with @holsandre on monday.

**Comment by Andreasr28** [comment]
Fix confirmed, the login works again. Doublecheck still pending.

**Comment by Andreasr28** [comment]
Confirmed. Close.
