### ISSUE TITLE
Change the design of "Delete WMS UI"

### ISSUE THREAD

**Issue by muqit-zoarder** [GDI-HE/Mapbender2.8#26]
In the context of changing the existing design of "deleting WMS UI" (mod_deleteWMS.php) it has been needed to apply bootstrap which will make the UI more user friendly and extends its scope.

**Before applying bootstrap:** 
_Please see below how it was look like before the update:_
![grafik](https://user-images.githubusercontent.com/98881990/214805962-b40298e0-00f7-4cda-b4bd-3f7d21ed4339.png)

**After applying bootstrap:**
_Please see below the changes:_

![grafik](https://user-images.githubusercontent.com/98881990/214806514-27c6531d-ca83-437e-83ea-0da4f5e3c701.png)

**Comment by karlbrink** [comment]
![grafik](https://github.com/GDI-HE/Mapbender2.8/assets/85093749/5cd30acc-5b27-46c6-a1a0-15e942bd3805)

![grafik](https://github.com/GDI-HE/Mapbender2.8/assets/85093749/b9c0eb7d-f625-4fc4-b7b7-046e1610b1a5)
