### ISSUE TITLE
WMC - Permitted characters for description 

### ISSUE THREAD

**Issue by Andreasr28** [GDI-HE/Mapbender2.8#61]
Allowed characters in the description of a WMC abstract 
currently allowed for all free text fields of the form
![grafik](https://github.com/user-attachments/assets/9b29cc3f-8f1f-4a8a-8291-e05a7f64055a)
![grafik](https://github.com/user-attachments/assets/e29c0720-980a-46d2-b7ca-0f9b8c2c044f)

The addition of the punctuation marks ! and ? would be helpful. Ideally only for the abstract field for the description of the card composition.

Addition: The ! is already included but is not displayed.

**Comment by Andreasr28** [comment]
Ty.

**Comment by dpakprajul** [comment]
Merged into master https://github.com/GDI-HE/Mapbender2.8/commit/93f5df047d0bf2761639ab91f0301f6928e70c88
